packages:
  - packages/e-commerce-api
  - packages/e-commerce-front
  - packages/api-client
  - packages/api-validation
  - packages/openapi-typespec
  - packages/e-commerce-search
  - packages/proto
  - packages/e-commerce-order

catalog:
  "@tanstack/react-query": ^5.101.4
  "@tanstack/react-query-devtools": ^5.101.4
  axios: ^1.15.0
  date-fns: ^4.1.0
  eslint: ^10.8.0
  next: ^16.1.6
  orval: ^7.9.0
  prettier: 3.5.3
  react: ^19.2.4
  react-dom: ^19.2.4
  typescript: ^5.9.3
  zod: ^4.3.6
